services:
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: ./fe/Dockerfile
    ports:
       - "4200:4200"
    networks:
      - app_network
  backend-server:
    container_name: backend-server
    build:
      context: .
      dockerfile: ./be/api/Dockerfile
    ports:
     - "3000:3000"
    restart: "unless-stopped"
    depends_on:
    - backend-postgis
    networks:
      - app_network
  backend-postgis:
    container_name: postgis
    build:
      context: .
      dockerfile: ./be/postgis-api/Dockerfile
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "unless-stopped"
    env_file:
      - .env
    networks:
      - app_network
volumes:
  pgdata:

networks:
  app_network:
    driver: bridge