services:
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: ./fe/Dockerfile
    ports:
       - "5432:5432" #PostgresSql with PostGis
       - "3000:3000" #Node.js API
    networks:
      - app_network
  backend:
    container_name: backend-api
    build:
      context: .
      dockerfile: ./be/Dockerfile
    ports:
     - "5001:5001"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./countries.geojson:/docker-entrypoint-initdb.d/countries.geojson:ro
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./app:/app
    restart: "unless-stopped"
    env_file:
      - .env
    networks:
      - app_network
networks:
  app_network:
    driver: bridge